version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ''  
      ME_CONFIG_BASICAUTH_PASSWORD: ''  
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongodb_data_container:
